version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/app/data/forum.db
    volumes:
      - ./data:/app/data
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./data:/app/data
